#!/bin/bash

RUN=$1
nEvents=$2
startEvent=$3

if [ "$#" -lt 3 ]; then
    echo "Usage:"
    echo "$ ./convertDUT <RUN> <nEvents> <startEvent>"
    exit
fi

fileNameIn=$(printf "$TBPATHININ/DUT_%06d.dat" $RUN)
fileNameOut=$(printf "$TBPATHOUTOUT/DUT_%06d_000000.root" $RUN)
fileNameCfg=$(printf "$TBPATHINCFG/run_%06d.cfg" $RUN)

root -b << EOF
.L convertDUT.C++
convertDUT("$fileNameIn", "$fileNameOut", "$fileNameCfg", $nEvents, $startEvent)
EOF

rm -rf convertDUT_C.*
