#!/bin/bash

RUN=$1
nEvents=$2
startEvent=$3

if [ "$#" -lt 2 ]; then
    echo "Usage:"
    echo "$ ./convertDUT <RUN> <nEvents> <startEvent>"
    exit
fi

#fileNameIn=$(printf "/eos/atlas/atlascerngroupdisk/pixel-upgrade/cmos/TowerJazz/Investigator/Testbeam/Testbeam2017/DUT_%06d.dat" $RUN)
fileNameIn=$(printf "../../../raw/DUT_%06d.dat" $RUN)
fileNameOut=$(printf "../../../output/DUT_%06d_000000.root" $RUN)
fileNameCfg=$(printf "../../../cfg/run_%06d.cfg" $RUN)

root -b << EOF
.L convertDUT.C++
convertDUT("$fileNameIn", "$fileNameOut", "$fileNameCfg", $nEvents, $startEvent)
EOF
