#!/bin/bash

RUN=$1
NEVENTS=$2

if [ "$#" -ne 2 ]; then
    echo "Usage:"
    echo "$ ./sync <RUN> <NEVENTS>"
    exit
fi

fileNameInTelescope=$(printf "$TBPATHINOUT/cosmic_%06d_000000-track-data.root" $RUN)
fileNameInDUT=$(printf "$TBPATHINOUT/DUT_%06d_000000.root" $RUN)
fileNameInCfg=$(printf "$TBPATHINCFG/run_%06d.cfg" $RUN)
fileNameOut=$(printf "$TBPATHOUTOUT/sync_%06d_000000.root" $RUN)

echo $fileNameInTelescope
echo $fileNameInDUT
echo $fileNameInCfg
echo $fileNameOut

root -b << EOF
.L synchronize.C++
synchronize("$fileNameInTelescope", "$fileNameInDUT", "$fileNameInCfg", "$fileNameOut", $NEVENTS)
EOF

rm -rf synchronize_C.*
