#!/bin/bash

RUN=$1
NEVENTS=$2

if [ "$#" -ne 2 ]; then
    echo "Usage:"
    echo "$ ./sync <RUN> <NEVENTS>"
    exit
fi

fileNameInTelescope=$(printf "$TBPATHOUT/cosmic_%06d_000000-track-data.root" $RUN)
fileNameInDUT=$(printf "$TBPATHOUT/DUT_%06d_000000.root" $RUN)
fileNameInCfg=$(printf "$TBPATHCFG/run_%06d.cfg" $RUN)
fileNameOut=$(printf "$TBPATHOUT/sync_%06d_000000.root" $RUN)

root -b << EOF
.L synchronize.C++
synchronize("$fileNameInTelescope", "$fileNameInDUT", "$fileNameInCfg", "$fileNameOut", $NEVENTS)
EOF

rm -rf synchronize_C.*
