[device]
name = "FEI4Tel"
clock = 40.0
window = 16
space_unit = "um"
time_unit = "ns"

[sensor_types.fei4-si]
measurement = "pixel_tot"
cols = 80
rows = 336
pitch_col = 250.0
pitch_row = 50.0
thickness = 250.0
x_x0 = 0.005443

[sensor_types.dummy]
measurement = "pixel_tot"
cols = 80
rows = 336
pitch_col = 250.0
pitch_row = 50.0
thickness = 250.0
x_x0 = 0.005443

# sensors in the order as they appear in the data file
# the index in this list corresponds to the sensor id in other configs

[[sensors]]
type = "fei4-si"

[[sensors]]
type = "fei4-si"

[[sensors]]
type = "fei4-si"

[[sensors]]
type = "fei4-si"

[[sensors]]
type = "fei4-si"

[[sensors]]
type = "fei4-si"